default: &default
  icanhazdadjoke:
    api_url: "https://icanhazdadjoke.com/search"
    headers:
      Accept: "application/json"
    timeout: 5
    max_limit: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
