production:
  daily_beehiiv_post:
    class: CreateDailyBeehiivPostJob
    queue: default
    schedule: at 9am every day

development:
  daily_beehiiv_post:
    class: CreateDailyBeehiivPostJob
    queue: default
    schedule: at 9am every day
