production:
  daily_beehiiv_post:
    class: CreateDailyBeehiivPostJob
    queue: default
    schedule: "0 14 * * *"

development:
  daily_beehiiv_post:
    class: CreateDailyBeehiivPostJob
    queue: default
    schedule: "0 14 * * *"
